# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=200)),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('image', models.FileField(default=b'No activity image', upload_to=b'')),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
