# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-23 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[(b'Contact Time', b'Contact Time'), (b'Independent Learning', b'Independent Learning')], default=b'Contact Time', max_length=200),
        ),
    ]
